# Generated by Django 4.1.6 on 2023-06-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_window_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
