# Generated by Django 4.1.6 on 2023-07-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queues', '0002_alter_operathor_word_end_alter_operathor_word_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operathor',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='queues.queue'),
        ),
        migrations.AlterField(
            model_name='operathor',
            name='operathor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operathor',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queues.window'),
        ),
    ]
