# Generated by Django 4.1.6 on 2023-06-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_rename_operator_queue_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='client',
            new_name='operator',
        ),
    ]
