# Generated by Django 4.2.2 on 2023-07-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_branches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branches',
        ),
    ]
