# Generated by Django 4.1.6 on 2023-06-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='code_activation',
            new_name='activation_code',
        ),
    ]
