# Generated by Django 4.1.6 on 2023-06-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_code_activation_ticket_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('not_active', 'Not active'), ('active', 'Active')], default='not_active', max_length=50),
        ),
    ]
