# Generated by Django 4.1.6 on 2023-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='activation_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('not_active', 'Not active'), ('active', 'Active')], default='not_active', max_length=50),
        ),
    ]
